
spring:
  application:
    name: feed
  servlet:
    multipart:
      max-file-size: 10GB
      max-request-size: 10GB
  main:
    allow-circular-references: true

  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: password
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
  hibernate:
    ddl-auto: update

  hikari:
    maximum-pool-size: 1
    minimum-idle: 5
