server:
  port: 8081

app:
  version: 1.0

spring:
  profiles:
    active: local

management:
  endpoints:
    web:
      exposure:
        include: '*'

springdoc:
  swagger-ui:
    path: /api/master/swagger-ui.html
  api-docs:
    path: /api/master/api-docs
  show-actuator: false